# -*- coding: utf-8 -*-
"""Mockintpart4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRkoCRFI5HppJMRUwuCeXGhu2hhTcRJ1
"""



"""# Task
Fine-tune a GPT-2 model for question answering using the `Software Questions.csv` dataset, create a function to evaluate user answers against ground truth answers using NLP techniques, and demonstrate both the model's answer generation and the answer evaluation function.

## Load and Prepare Dataset

### Subtask:
Load the 'Software Questions.csv' dataset into a Pandas DataFrame, preprocess the text, and split it into training and testing sets. The data will be formatted appropriately for GPT-2 fine-tuning, likely concatenating questions and answers.

**Reasoning**:
The first step is to import the pandas library and load the 'Software Questions.csv' file into a DataFrame. Then, I will inspect the first few rows to understand its structure.
"""

import pandas as pd

df = pd.read_csv('/content/Software Questions.csv')
df.head()

"""**Reasoning**:
The previous `pd.read_csv` command failed with a `UnicodeDecodeError` because the file was not encoded in UTF-8. I will try loading the CSV file again, but this time specifying the 'latin1' encoding, which often resolves such issues.


"""

import pandas as pd

df = pd.read_csv('/content/Software Questions.csv', encoding='latin1')
df.head()

"""**Reasoning**:
Now that the data is loaded, I will create a new column by concatenating the 'Question' and 'Answer' columns into a single text string. This format is suitable for GPT-2 input. Afterward, I will split the preprocessed DataFrame into training and testing sets using `train_test_split` from `sklearn.model_selection` to prepare the data for model training.


"""

df['text'] = 'Question: ' + df['Question'] + ' Answer: ' + df['Answer']

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

print(f"Training set shape: {train_df.shape}")
print(f"Testing set shape: {test_df.shape}")
print("First entry of the 'text' column in the training set:")
print(train_df['text'].iloc[0])

"""## Initialize GPT-2 Model and Tokenizer

### Subtask:
Load the pre-trained GPT-2 model and its corresponding tokenizer from the Hugging Face `transformers` library. Configure the tokenizer for padding and truncation.

**Reasoning**:
I need to import the necessary classes from the `transformers` library, load the pre-trained GPT-2 tokenizer and model, and then configure the tokenizer's padding token to its end-of-sequence token.
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer

# 2. Load the pre-trained GPT-2 tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

# 3. Load the pre-trained GPT-2 model for causal language modeling
model = GPT2LMHeadModel.from_pretrained('gpt2')

# 4. Set the padding token for the tokenizer to its end-of-sequence (eos) token
tokenizer.pad_token = tokenizer.eos_token

print("GPT-2 tokenizer and model loaded successfully.")

"""**Reasoning**:
The previous steps successfully loaded and preprocessed the data, and initialized the GPT-2 tokenizer and model. The next logical step is to tokenize the prepared dataset (`train_df` and `test_df`) using the loaded tokenizer, which is a necessary step before fine-tuning the GPT-2 model.


"""

def tokenize_function(examples):
    return tokenizer(examples['text'], truncation=True, padding='max_length', max_length=512)

train_tokenized = train_df.apply(tokenize_function, axis=1)
test_tokenized = test_df.apply(tokenize_function, axis=1)

print(f"First tokenized training example input IDs: {train_tokenized.iloc[0]['input_ids'][:20]}...")
print(f"First tokenized training example attention mask: {train_tokenized.iloc[0]['attention_mask'][:20]}...")

"""**Reasoning**:
The tokenized data (`train_tokenized` and `test_tokenized`) is currently in a Pandas Series of dictionaries. To prepare this data for fine-tuning with the Hugging Face `Trainer` API, it needs to be converted into a compatible format, specifically `Dataset` objects from the `datasets` library. This involves converting the Series into a list of dictionaries and then using `Dataset.from_dict`.


"""

from datasets import Dataset

# Convert tokenized data (Series of dicts) to a list of dicts for Dataset.from_dict
train_data_list = train_tokenized.tolist()
test_data_list = test_tokenized.tolist()

# Convert the list of dictionaries to Hugging Face Dataset objects
train_dataset = Dataset.from_list(train_data_list)
test_dataset = Dataset.from_list(test_data_list)

# For causal language modeling, the labels are typically the input_ids themselves
def add_labels(example):
    example["labels"] = example["input_ids"]
    return example

train_dataset = train_dataset.map(add_labels, batched=True)
test_dataset = test_dataset.map(add_labels, batched=True)

print("Training dataset and testing dataset created successfully.")
print(f"First training dataset example: {train_dataset[0]}")

"""**Reasoning**:
The data is now prepared as `Dataset` objects with input IDs and labels. The next step is to define the training arguments required for fine-tuning the GPT-2 model, such as output directory, number of epochs, batch sizes, and logging steps. This is a prerequisite before initializing the Hugging Face `Trainer`.


"""

from transformers import TrainingArguments, Trainer

# 6. Define TrainingArguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,  # You can adjust this
    per_device_train_batch_size=2,  # Adjust based on your GPU memory
    per_device_eval_batch_size=2,  # Adjust based on your GPU memory
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_as_init_checkpoint=True,
    report_to="none" # Disable experiment tracking if not needed
)

print("Training arguments defined successfully.")

"""**Reasoning**:
The previous code failed with a `TypeError` indicating that `evaluation_strategy` is an unexpected keyword argument for `TrainingArguments`. This suggests an older version of the `transformers` library is in use where this argument, along with `save_strategy` and `load_best_model_as_init_checkpoint`, might not be directly supported in the constructor. To fix this, I will remove these unsupported arguments.


"""

from transformers import TrainingArguments, Trainer

# 6. Define TrainingArguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,  # You can adjust this
    per_device_train_batch_size=2,  # Adjust based on your GPU memory
    per_device_eval_batch_size=2,  # Adjust based on your GPU memory
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
    report_to="none" # Disable experiment tracking if not needed
)

print("Training arguments defined successfully.")

"""**Reasoning**:
The training arguments have been successfully defined. The next logical step is to initialize the Hugging Face `Trainer` object, passing in the pre-trained model, the defined training arguments, and the prepared training and evaluation datasets. This sets up the environment for the fine-tuning process.


"""

from transformers import DataCollatorForLanguageModeling

# Initialize Data Collator
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# 7. Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator
)

print("Trainer initialized successfully.")

"""## Fine-tune GPT-2 Model

### Subtask:
Fine-tune the GPT-2 model on the training data using the initialized `Trainer` object.

**Reasoning**:
With the `Trainer` object initialized, I will now start the fine-tuning process by calling the `.train()` method to fine-tune the GPT-2 model on the training data.
"""

trainer.train()
print("Model fine-tuning completed.")

"""**Reasoning**:
The previous steps successfully fine-tuned the GPT-2 model. The next logical step is to define a function that utilizes this fine-tuned model to generate answers for new questions, leveraging the tokenizer and model from the earlier steps.


"""

def generate_answer(question, model, tokenizer, max_length=100):
    input_text = "Question: " + question + " Answer: "
    input_ids = tokenizer.encode(input_text, return_tensors='pt')

    # Generate text
    output_ids = model.generate(
        input_ids,
        max_length=max_length,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        pad_token_id=tokenizer.eos_token_id,
        top_k=50,
        top_p=0.95,
        temperature=0.7
    )

    generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    # Extract only the answer part if the model generates more than just the answer
    answer_start = generated_text.find("Answer:")
    if answer_start != -1:
        generated_answer = generated_text[answer_start + len("Answer:"):].strip()
    else:
        generated_answer = generated_text.strip()

    # Remove the original question from the answer if it was repeated
    if generated_answer.startswith(question):
        generated_answer = generated_answer[len(question):].strip()

    return generated_answer

print("Answer generation function defined.")

"""## Develop Answer Evaluation Function

### Subtask:
Create a Python function that takes a user's answer and the ground truth answer, compares them using NLP techniques, and returns a ranking from 1 to 10.

**Reasoning**:
I will import the necessary libraries, including `SentenceTransformer` and `cosine_similarity`, and then define the `evaluate_answer` function that generates embeddings for user and ground truth answers, calculates cosine similarity, and maps it to a 1-10 ranking.
"""

try:
    from sentence_transformers import SentenceTransformer
    from sklearn.metrics.pairwise import cosine_similarity
except ImportError:
    print("Installing sentence-transformers and scikit-learn...")
    !pip install -qq sentence-transformers scikit-learn
    from sentence_transformers import SentenceTransformer
    from sklearn.metrics.pairwise import cosine_similarity

# 1. Load a pre-trained SentenceTransformer model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Define the evaluation function
def evaluate_answer(user_answer: str, ground_truth_answer: str) -> int:
    """
    Compares a user's answer against a ground truth answer using NLP techniques
    and returns a ranking from 1 to 10.

    Args:
        user_answer (str): The answer provided by the user.
        ground_truth_answer (str): The correct ground truth answer.

    Returns:
        int: A ranking from 1 to 10, where 10 is a perfect match.
    """
    # Generate sentence embeddings for both answers
    user_embedding = embedding_model.encode([user_answer])
    ground_truth_embedding = embedding_model.encode([ground_truth_answer])

    # Calculate the cosine similarity between the two embeddings
    similarity_score = cosine_similarity(user_embedding, ground_truth_embedding)[0][0]

    # Map the cosine similarity score (0 to 1) to a ranking from 1 to 10
    # We scale it from 0 to 1 and then map to 1-10.
    # Since cosine_similarity typically returns values between -1 and 1,
    # but for semantic similarity, values closer to 0 or positive are common.
    # We'll assume typical values are in [0, 1] for this mapping.
    # A linear mapping: score * 9 + 1 (to get a range of 1-10)
    # If similarity can be negative, clip it at 0.
    normalized_similarity = max(0, similarity_score)
    ranking = int(normalized_similarity * 9) + 1

    # Ensure ranking is within 1-10 range due to possible floating point issues or edge cases
    ranking = max(1, min(10, ranking))

    return ranking

print("Answer evaluation function 'evaluate_answer' defined.")

"""**Reasoning**:
The previous steps successfully defined functions for both answer generation and answer evaluation. The next logical step is to demonstrate these functions by picking a question from the test set, using the fine-tuned model to generate an answer, retrieving the ground truth answer, and then evaluating the generated answer against the ground truth using the `evaluate_answer` function.


"""

import random

# 1. Pick a random question from the test set
random_idx = random.randint(0, len(test_df) - 1)
question_data = test_df.iloc[random_idx]
question = question_data['Question']
ground_truth_answer = question_data['Answer']

print(f"Original Question: {question}")
print(f"Ground Truth Answer: {ground_truth_answer}")

# 2. Generate an answer using the fine-tuned GPT-2 model
# Ensure the model and tokenizer are defined and loaded from previous steps
generated_ans = generate_answer(question, model, tokenizer, max_length=150)
print(f"Generated Answer: {generated_ans}")

# 3. Evaluate the generated answer against the ground truth
ranking = evaluate_answer(generated_ans, ground_truth_answer)
print(f"Evaluation Ranking (1-10): {ranking}")

"""**Reasoning**:
The previous code failed because the `generate` method received unsupported parameters (`temperature`, `top_p`) and an `attention_mask` was not explicitly provided, leading to warnings and potentially unexpected behavior. I will modify the `generate_answer` function to pass the `attention_mask` correctly and remove the unsupported parameters from the `model.generate` call.


"""

def generate_answer(question, model, tokenizer, max_length=100):
    input_text = "Question: " + question + " Answer: "

    # Use tokenizer to get both input_ids and attention_mask
    encoded_input = tokenizer(input_text, return_tensors='pt', padding=True, truncation=True)
    input_ids = encoded_input['input_ids']
    attention_mask = encoded_input['attention_mask']

    # Generate text, passing the attention_mask and removing unsupported parameters
    output_ids = model.generate(
        input_ids,
        attention_mask=attention_mask,
        max_length=max_length,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        pad_token_id=tokenizer.eos_token_id
        # Removed top_k, top_p, and temperature as they caused warnings/errors in this context.
        # The default generation strategy (greedy search) will be used.
    )

    generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)

    # Extract only the answer part if the model generates more than just the answer
    # It's more robust to remove the exact input_text from the generated_text
    if generated_text.startswith(input_text):
        generated_answer = generated_text[len(input_text):].strip()
    else:
        generated_answer = generated_text.strip()

    return generated_answer

print("Answer generation function defined.")

"""**Reasoning**:
The `generate_answer` function has been updated in the previous step to handle generation parameters and attention masks correctly. Now, I will re-run the demonstration of answer generation and evaluation to confirm the fix and observe the new behavior.


"""

import random

# 1. Pick a random question from the test set
random_idx = random.randint(0, len(test_df) - 1)
question_data = test_df.iloc[random_idx]
question = question_data['Question']
ground_truth_answer = question_data['Answer']

print(f"Original Question: {question}")
print(f"Ground Truth Answer: {ground_truth_answer}")

# 2. Generate an answer using the fine-tuned GPT-2 model
# Ensure the model and tokenizer are defined and loaded from previous steps
generated_ans = generate_answer(question, model, tokenizer, max_length=150)
print(f"Generated Answer: {generated_ans}")

# 3. Evaluate the generated answer against the ground truth
ranking = evaluate_answer(generated_ans, ground_truth_answer)
print(f"Evaluation Ranking (1-10): {ranking}")

"""## Final Task

### Subtask:
Provide a summary of the fine-tuned model and the implemented answer evaluation system, along with instructions on how to interact with it.

## Summary:

### Q&A
The fine-tuned model is a GPT-2 model adapted for question answering on software-related questions. The implemented answer evaluation system uses NLP techniques (specifically, `SentenceTransformer` for semantic similarity) to compare a generated answer against a ground truth answer, providing a ranking from 1 to 10.

To interact with the system:
1.  **Generate an Answer**: Call the `generate_answer(question, model, tokenizer, max_length)` function, passing your question string, the fine-tuned GPT-2 model, its tokenizer, and an optional maximum length for the generated answer. This will return the model's generated response to your question.
2.  **Evaluate an Answer**: Call the `evaluate_answer(generated_answer, ground_truth_answer)` function, providing the answer you want to evaluate (e.g., the model's generated answer or a user's answer) and the correct ground truth answer. The function will return a numerical ranking from 1 to 10, indicating the semantic similarity between the two answers, where 10 is the highest similarity.

### Data Analysis Key Findings
*   The `Software Questions.csv` dataset was successfully loaded by specifying `encoding='latin1'` and contained 200 entries.
*   A new 'text' column was created, concatenating 'Question' and 'Answer' to form 'Question: \[question\_text] Answer: \[answer\_text]', suitable for language model training.
*   The dataset was split into training (160 samples) and testing (40 samples) sets.
*   A pre-trained GPT-2 model and its tokenizer were successfully loaded, and the tokenizer's padding token was configured to its end-of-sequence token.
*   The GPT-2 model was fine-tuned on the prepared training data.
*   An `evaluate_answer` function was developed using `SentenceTransformer` ('all-MiniLM-L6-v2') to calculate cosine similarity between answer embeddings, mapping this similarity to a 1-10 ranking.
*   The `generate_answer` function was refined to ensure robust answer generation by correctly handling `attention_mask` and removing unsupported generation parameters, leading to clean answer outputs from the fine-tuned model.
*   Demonstrations showed the `evaluate_answer` function successfully providing rankings (e.g., 4 or 7) for generated answers against ground truth answers.

### Insights or Next Steps
*   The fine-tuned GPT-2 model is capable of generating contextually relevant answers to software-related questions, and the `evaluate_answer` function provides a quantitative measure of answer quality based on semantic similarity.
*   Future work could involve exploring different similarity metrics or more advanced NLP evaluation techniques (e.g., ROUGE, BLEU scores) within the `evaluate_answer` function, or integrating human feedback for a more nuanced evaluation of answer quality.
"""

import random

# 1. Pick a random question from the test set
random_idx = random.randint(0, len(test_df) - 1)
question_data = test_df.iloc[random_idx]
question_to_ask = question_data['Question']
ground_truth_for_evaluation = question_data['Answer']

print(f"Question for you: {question_to_ask}")

# 2. Get user input for the answer
user_response = input("Please enter your answer: ")

print(f"\nYour Answer: {user_response}")
print(f"Ground Truth Answer: {ground_truth_for_evaluation}")

# 3. Evaluate the user's answer against the ground truth
ruser_anking = evaluate_answer(user_response, ground_truth_for_evaluation)
print(f"\nEvaluation Ranking (1-10) for your answer: {ruser_anking}")

# Optional: Provide some basic feedback based on ranking
if ruser_anking >= 8:
    print("Feedback: Excellent! Your answer is very close to the ground truth.")
elif ruser_anking >= 5:
    print("Feedback: Good effort! Your answer is reasonably similar to the ground truth.")
else:
    print("Feedback: Keep learning! Your answer has some differences from the ground truth.")